VirtoCommerce/vc-theme-default

assets/common-components.css, assets/js/bulk-order.js, assets/js/main.js, snippets/breadcrumb.liquid, snippets/bulk-order-fields-column.liquid, templates/bulk-order.liquid
<details><summary>CSV</summary><p>
<details><summary>SKU</summary><p>
[ticket #4](https://github.com/VirtoCommerce/vc-theme-default/issues/4)
[ticket #5](https://github.com/VirtoCommerce/vc-theme-default/issues/5)
=> bulk order

assets/default.scss.liquid, snippets/badges.liquid, snippets/product-grid-item.liquid, snippets/product-list-item.liquid
If product quantity = 0 but product can be purchased we can see "sold out". If product can`t be purchased we can see "unavailable".
=> if product can`t be purshed show unavailable

templates/customers/register.liquid
=> revert form data if error

gulpfile.js
=> excluded node_modules folder

locales/en.default.json, templates/customers/forgot_password_code.liquid
- Added forgot_password_code form
=> #73 Reset password confirmation by SMS

snippets/collection-sorting.liquid
- Changed Featured sort element value from "manual" to "priority-descending;name-ascending";
=> "Featured" sorting is now working properly #248:

README.md
These are the problems I came across and I mentioned it earlier.
[Now it looks](https://github.com/kamilgarey/vc-theme-default/tree/dev-minification-issues-were-add-to-description)
=> Minificaton issues were added to description

snippets/collection-sorting.liquid
=> fix wrong value for sorting options,comment best-selling option since it's not working correctly for now

snippets/tag-label.liquid
fix for https://github.com/VirtoCommerce/vc-storefront-core/issues/313#issue-500075344
=> fix position for decimal separator in price facet filter

snippets/footer.liquid
fix for https://github.com/VirtoCommerce/vc-theme-default/issues/116
=> fix footer links with absolute_url filter

snippets/recently-added-actual-quote-request-item-dialog.liquid, templates/customers/quote-requests.liquid
fix for https://virtocommerce.atlassian.net/browse/VP-786
=> redirect on adding new quote and fix error on submitting

assets/js/account/account-password-change.js, assets/js/account/account-password-change.tpl.liquid
fix for https://virtocommerce.atlassian.net/browse/VP-568
=> rename change password model newPassword2=>newPasswordConfirm

templates/bulk-order.liquid
=> fix error message in "bulk order"

assets/js/product.js, templates/product.liquid
Disable unavailable options when selecting a product.
=> Dev 120 manage sku selector options

assets/js/account/account-addresses.tpl.liquid
Fixed by extending parent container
=> VP-1188: Fix Apt placeholder in Address

locales/de.json
Change translation from "Einkaufswagen" to "Warenkorb"
=> vp-1230_Wrong_style_menu_in_de-DE_language

snippets/recently-added-list-item-dialog.liquid
=> vp1227_list_name_missing

locales/en.default.json, snippets/footer.liquid
Remove the content from the footer
=> 1202_Add(Remove)_content_in_footer_block

layout/account_layout.liquid, layout/checkout_layout.liquid
=> vp-1237_redundant_inks

templates/customers/forgot_login.liquid, templates/customers/forgot_password.liquid
don't show success and errors simultaneously.
=> vp-1234_Incorrect_error_in_forgot_password

assets/js/lists/account-lists.js, assets/js/lists/add-to-list.js, snippets/recently-added-list-item-dialog.liquid
Fix do not open user list selected above
=> vp-1229_view_you_list

assets/js/common-components/address.js
=> vp-1254_Format_address_in_Selected_address_field

config/settings_data.json, snippets/newsletter-form.liquid
fix 500 error when try to sing up
=> vp-1253_fix_sign_up_for_newsletter

snippets/search-bar.liquid, templates/customers/addresses.liquid, templates/search.liquid
Add 'escape' where needed, remove 'escape' where unnecessary
=> VP-1629 Character Escaping on search bar value.

snippets/quick-order-section.liquid
Disables liquid tag processing for one row
=> VP-1228: Absent preview of products in search on empty cart page

assets/js/products-compare/product-compare.js
Add variation properties to compare list
=> VP-1231: Variation properties absent in compare list

templates/product.liquid
VP-1755: Add a condition to view to hide hidden property
=> VP-1755: Hidden properties are shown on storefront

assets/js/common-components/paymentMethods.js
VP-1948: Update cart payments when the checkout wizard step "Payment method" opening
=> VP-1948: Wrong order total amount in Authorize.net module

assets/js/checkout/checkout.js, layout/checkout_layout.liquid
Payment plan don't work correctly
Period don't change due navigating on order creation
Add comparing period case insensitive method.
=> VP-1947: Storefront - Auto order frequency resets when you go to the next stage of order creating

snippets/recently-added-actual-quote-request-item-dialog.liquid
=> VP-1197: Fix redirect to empty quote request

snippets/product-compare.liquid
Fixed behavior for True and False values with value type Boolean
=> VP-1747: Display property with value type Boolean in compare list

assets/js/quote-request.js, assets/js/services.js, locales/en.default.json, templates/quote-request.liquid
Added "Remove all items" button with corresponding functionality
=> VP-3540: Implement "Remove all quote items" functionality

templates/customers/forgot_password.liquid
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.
=> #VP-2311 forgot password by login
